#!/usr/bin/env python

import argparse
import sys
from core import libretto

sys.setrecursionlimit(20000)


parser = argparse.ArgumentParser()
parser.add_argument("fileLog", default="", nargs="?",
                    help="file is the filename of the log")

parser.add_argument("--fullscreen", help="increase output verbosity",
                    action="store_true")


#################################################
#                        MAIN                   #
#################################################
if __name__ == '__main__':
    args = parser.parse_args()
    fileLog = args.fileLog
    if file == "":
        fileLog = None
    libretto.Call_Reader(fileLog, fullscreen=args.fullscreen)
